!LCM OF TWO NUMBERS
PROGRAM LCM
 IMPLICIT NONE
 INTEGER::N1,N2,RES,I,J,FACT=1,TEMP1,TEMP2,N
 PRINT*,"ENTER FIRST NO"
  READ*,N1
 PRINT*,"ENTER SECOND NO"
  READ*,N2
TEMP1=N1
TEMP2=N2
IF(N1>N2)THEN
 N=N1
ELSE
 N=N2
ENDIF
DO I=1,N
 IF(MOD(TEMP1,I)==0 .AND. MOD(TEMP2,I)==0)THEN
 IF(FACT<I)THEN
  FACT=I
 ENDIF
 ENDIF
END DO
!FACT MEANS GREATEST COMMON DIVISOR
RES=FACT*(N1/FACT)*(N2/FACT)
PRINT*,"LCM=",RES
END PROGRAM LCM
 
